# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "yunotest" do |yunotest|
    yunotest.vm.box = "generic/debian10"
    yunotest.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      #ansible.verbose = "vvv"
    end
    yunotest.vm.provider :libvirt do |libvirt|
      libvirt.memory = 3072
    end
    yunotest.vm.synced_folder "/mnt/c/projet2022/restic-s3-yunohost", "/restic-s3-yunohost"
  end
  config.vm.define "minio" do |minio|
    minio.vm.box = "minio/minio"
  end
end
